language: android
android:
  components:
    - build-tools-26.0.2
    - android-27
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-27

  licenses:
    - '.+'

  script:
    - ./gradlew clean test